# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textapp', '0003_sometext_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sometext',
            old_name='some_text',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='sometext',
            old_name='some_text2',
            new_name='name',
        ),
        migrations.AddField(
            model_name='sometext',
            name='username',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
