# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textapp', '0004_auto_20170220_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sometext',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
